# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar100

np.random.seed(100)

# 資料準備

In [2]:
(x_train, y_train), (x_test, y_test) = cifar100.load_data(label_mode="fine")

169001437/169001437 [==============================] - 197s 1us/step


In [3]:
print("train:", len(x_train))
print("test:", len(x_test))

train: 50000
test: 10000


In [4]:
# each is composed of 32x32 rgb colours, with pixel values range from 0 to 255
x_train.shape

(50000, 32, 32, 3)

In [5]:
y_train.shape

(50000, 1)

# Image normalize 

In [10]:
x_train_normalize = x_train / 255
x_test_normalize = x_test / 255

In [12]:
x_train_normalize[5][5][5]

array([0.81960784, 0.69019608, 0.52941176])

# 轉換label 為OneHot Encoding

In [15]:
y_train.shape

(50000, 1)

In [14]:
y_train[:5]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1]])

In [16]:
y_train_OneHot = tf.keras.utils.to_categorical(y_train)
y_test_OneHot = tf.keras.utils.to_categorical(y_test)

In [17]:
y_train_OneHot[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)